using System.Globalization;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Maui.Controls;

namespace CCT_USCF.Services;

internal static class AppLocalization
{
    private static readonly IReadOnlyDictionary<string, (string English, string Swahili)> Strings =
        new Dictionary<string, (string English, string Swahili)>
        {
            ["Shell.Home"] = ("Home", "Nyumbani"),
            ["Shell.Prayer"] = ("Prayer", "Maombi"),
            ["Shell.Community"] = ("Community", "Jamii"),
            ["Shell.Profile"] = ("Profile", "Wasifu"),
            ["Shell.Assistance"] = ("Open USCF Assistance", "Fungua Msaada wa USCF"),
            ["Shell.SignUpLogin"] = ("Sign Up / Login", "Jisajili / Ingia"),
            ["Shell.OpenAuth"] = ("Open authentication actions", "Fungua chaguo za kuingia"),

            ["Home.Title"] = ("Home", "Nyumbani"),
            ["Home.ChurchHeadquarters"] = ("My church headquarters", "Makao makuu ya kanisa langu"),
            ["Home.WelcomeBack"] = ("WELCOME BACK 👋", "KARIBU TENA 👋"),
            ["Home.GoodMorning"] = ("GOOD MORNING", "HABARI ZA ASUBUHI"),
            ["Home.GoodAfternoon"] = ("GOOD AFTERNOON", "HABARI ZA MCHANA"),
            ["Home.GoodEvening"] = ("GOOD EVENING", "HABARI ZA JIONI"),
            ["Home.CommunityActive"] = ("Your USCF community is active today.", "Jumuiya yako ya USCF inaendelea leo."),
            ["Home.SignInChurch"] = ("Sign in to see your church context.", "Ingia ili kuona taarifa za kanisa lako."),
            ["Home.LoadingChurch"] = ("Your church context is loading...", "Taarifa za kanisa lako zinapakia..."),
            ["Home.ViewProfile"] = ("View your profile  ›", "Tazama wasifu wako  ›"),
            ["Home.TodayInUscf"] = ("Today in USCF", "Leo USCF"),
            ["Home.ViewActivities"] = ("View all activities  ›", "Tazama shughuli zote  ›"),
            ["Home.Announcements"] = ("Announcements", "Matangazo"),
            ["Home.PrayerRequests"] = ("Prayer Requests", "Maombi"),
            ["Home.CommunityActivity"] = ("Community activity", "Shughuli za jamii"),
            ["Home.ChurchActivity"] = ("Church activity", "Shughuli za kanisa"),
            ["Home.MyChurch"] = ("My Church", "Kanisa Langu"),
            ["Home.Open"] = ("Open  ›", "Fungua  ›"),
            ["Home.OrganizationPlaceholder"] = ("Your organization will appear here.", "Taarifa za kanisa lako zitaonekana hapa."),
            ["Home.ChurchUnavailable"] = ("Church context unavailable", "Taarifa za kanisa hazipatikani"),
            ["Home.MemberCountUnavailable"] = ("Member count is not available from the current services.", "Idadi ya waumini haipatikani kwa sasa."),
            ["Home.OpenMyChurch"] = ("Open My Church", "Fungua Kanisa Langu"),
            ["Home.OfficialUpdate"] = ("OFFICIAL USCF UPDATE", "TAARIFA RASMI ZA USCF"),
            ["Home.NoAnnouncements"] = ("No new announcements", "Hakuna matangazo mapya"),
            ["Home.CaughtUp"] = ("You're all caught up.", "Umesasishwa na taarifa zote."),
            ["Home.ViewAnnouncements"] = ("View announcements  ›", "Tazama matangazo  ›"),
            ["Home.YourGroups"] = ("Your Church Groups", "Vikundi vya Kanisa Lako"),
            ["Home.SeeAll"] = ("See all  ›", "Tazama zote  ›"),
            ["Home.Groups"] = ("Church Groups", "Vikundi vya Kanisa"),
            ["Home.ChooseGroupLevel"] = ("Choose a level to view available groups.", "Chagua ngazi ili kuona vikundi vinavyopatikana."),
            ["Home.PrayWithCommunity"] = ("PRAY WITH YOUR COMMUNITY", "OMBA PAMOJA NA JAMII YAKO"),
            ["Home.PrayerPreview"] = ("Prayer requests will appear here when available.", "Maombi yataonekana hapa yatakapopatikana."),
            ["Home.OpenPrayerWall"] = ("Open prayer wall  ›", "Fungua ukuta wa maombi  ›"),
            ["Home.TodayWord"] = ("Today's Word", "Neno la Leo"),
            ["Home.ReadPassage"] = ("Read passage  ›", "Soma kifungu  ›"),
            ["Home.TodayWordUpper"] = ("TODAY'S WORD", "NENO LA LEO"),
            ["Home.UscfCommunity"] = ("USCF Community", "Jumuiya ya USCF"),
            ["Home.NewSermon"] = ("New sermon", "Mahubiri Mapya"),
            ["Home.PlusPosts"] = ("PLUS Posts", "Machapisho ya PLUS"),
            ["Home.Refresh"] = ("Refresh  ›", "Onyesha upya  ›"),
            ["Home.LoadingPosts"] = ("Loading posts...", "Machapisho yanapakia..."),
            ["Home.NoPostsYet"] = ("No posts available yet.", "Hakuna machapisho kwa sasa."),
            ["Home.NoPostsOffline"] = ("No posts available offline.", "Hakuna machapisho yanayopatikana nje ya mtandao."),
            ["Home.PublishedPosts"] = ("{0} published post{1}", "Machapisho {0} yaliyochapishwa"),
            ["Home.UpcomingActivity"] = ("Upcoming Church Activity", "Shughuli Zijazo za Kanisa"),
            ["Home.NoUpcomingActivity"] = ("No upcoming activity available.", "Hakuna shughuli zijazo zinazopatikana."),
            ["Home.NoPrayerNow"] = ("No prayer requests are available right now.", "Hakuna maombi yanayopatikana kwa sasa."),
            ["Home.PrayerUnavailable"] = ("Prayer requests temporarily unavailable.", "Maombi hayapatikani kwa sasa."),
            ["Home.AnnouncementsUnavailable"] = ("Announcements temporarily unavailable", "Matangazo hayapatikani kwa sasa"),
            ["Home.TryAgainLater"] = ("Please try again later.", "Tafadhali jaribu tena baadaye."),
            ["Home.ActivityUnavailable"] = ("Church activity temporarily unavailable.", "Shughuli za kanisa hazipatikani kwa sasa."),
            ["Home.NoUpcomingChurchActivity"] = ("No upcoming church activity available.", "Hakuna shughuli za kanisa zijazo zinazopatikana."),
            ["Home.ActivitiesAvailable"] = ("{0} community activities available. Open Events to view them.", "Shughuli {0} za jamii zinapatikana. Fungua Matukio ili kuzitazama."),
            ["Home.OpenEvents"] = ("Events", "Matukio"),
            ["Home.GoodToSeeYou"] = ("Good to see you, {0}.", "Nimefurahi kukuona, {0}."),
            ["Home.ViewAnnouncement"] = ("View announcement  ›", "Tazama tangazo  ›"),
            ["Home.ShareServe"] = ("✨ Share & Serve", "✨ Shiriki na Hudumia"),
            ["Home.ContributePrompt"] = ("What would you like to contribute?", "Ungependa kuchangia nini?"),
            ["Home.CloseShareServe"] = ("Close Share and Serve menu", "Funga menyu ya Shiriki na Hudumia"),
            ["Home.Scripture"] = ("📖  Scripture", "📖  Maandiko"),
            ["Home.Prayer"] = ("🙏  Prayer", "🙏  Maombi"),
            ["Home.Encouragement"] = ("💬  Encouragement", "💬  Maneno ya kutia moyo"),
            ["Home.Notice"] = ("📢  Notice", "📢  Taarifa"),
            ["Home.Worship"] = ("🎵  Worship", "🎵  Ibada"),
            ["Home.Event"] = ("📅  Event", "📅  Tukio"),
            ["Common.Close"] = ("Close", "Funga"),
            ["Home.ShortcutAnnouncements"] = ("Announcements  !", "Matangazo  !"),
            ["Home.ShortcutEvents"] = ("Events  □", "Matukio  □"),
            ["Home.ShortcutSermons"] = ("Sermons  ▶", "Mahubiri  ▶"),
            ["Home.ShortcutGiving"] = ("Giving  ＋", "Michango  ＋"),
            ["Home.OpenShortcuts"] = ("Open quick shortcuts", "Fungua njia za mkato"),
            ["Home.PostType.Scripture"] = ("📖 SCRIPTURE", "📖 MAANDIKO"),
            ["Home.PostType.Encouragement"] = ("💬 ENCOURAGEMENT", "💬 MANENO YA KUTIA MOYO"),
            ["Home.PostType.Worship"] = ("🎵 WORSHIP", "🎵 IBADA"),
            ["Home.PostType.Prayer"] = ("🙏 PRAYER", "🙏 MAOMBI"),
            ["Home.PostType.Notice"] = ("📢 NOTICE", "📢 TAARIFA"),
            ["Home.PostType.Event"] = ("📅 EVENT", "📅 TUKIO"),
            ["Home.PlayVideo"] = ("▶ Play video", "▶ Cheza video"),
            ["Home.PlayAudio"] = ("▶ Play audio", "▶ Cheza sauti"),
            ["Home.OpenVideo"] = ("▶ Open video", "▶ Fungua video"),
            ["Home.OpenAudio"] = ("▶ Open audio", "▶ Fungua sauti"),
            ["Home.OpenDocument"] = ("↗ Open document", "↗ Fungua hati"),
            ["Home.Posted"] = ("Posted {0}", "Imechapishwa {0}"),

            ["Prayer.Title"] = ("Prayer", "Maombi"),
            ["Prayer.Community"] = ("Prayer Community", "Jumuiya ya Maombi"),
            ["Prayer.LetUsPray"] = ("Let us pray for one another.", "Tuombeane."),
            ["Prayer.Wall"] = ("Prayer Wall", "Ukuta wa Maombi"),
            ["Prayer.MyRequests"] = ("My Requests", "Maombi Yangu"),
            ["Prayer.CommunityTab"] = ("Community", "Jamii"),
            ["Prayer.AddRequest"] = ("＋  Add Prayer Request", "＋  Ongeza Ombi la Maombi"),
            ["Prayer.OpenForm"] = ("Open the prayer request form", "Fungua fomu ya ombi la maombi"),
            ["Prayer.EmptyTitle"] = ("No prayer requests yet", "Bado hakuna maombi"),
            ["Prayer.EmptyDescription"] = ("Be the first to share a prayer request with the community.", "Kuwa wa kwanza kushiriki ombi la maombi na jamii."),
            ["Prayer.Anonymous"] = ("(Anonymous)", "(Bila jina)"),
            ["Prayer.IPray"] = ("🙏  I PRAY", "🙏  NINAOMBA"),
            ["Prayer.IPrayed"] = ("🙏  I PRAYED", "🙏  NIMEOMBA"),
            ["Prayer.PrayForRequest"] = ("Pray for this request", "Ombea ombi hili"),
            ["Prayer.PeoplePrayed"] = ("people prayed", "watu wameomba"),
            ["Prayer.PrayedWithYouSuffix"] = ("people prayed with you", "wamekuombea"),
            ["Prayer.PostedPrefix"] = ("Posted", "Imechapishwa"),
            ["Prayer.Loading"] = ("Loading prayer requests...", "Maombi yanapakia..."),
            ["Prayer.LoadError"] = ("Couldn't load prayer requests.", "Imeshindikana kupakia maombi."),
            ["Prayer.TryAgain"] = ("Try Again", "Jaribu Tena"),
            ["Prayer.Welcome"] = ("WELCOME TO THE PRAYER COMMUNITY", "KARIBU KWENYE JUMUIYA YA MAOMBI"),
            ["Prayer.WelcomeDescription"] = ("You don't have to pray alone. Share a prayer request and let members of the USCF family stand with you.", "Huhitaji kuomba peke yako. Shiriki ombi la maombi na waache wanajumuiya wa USCF waungane nawe."),
            ["Prayer.GotIt"] = ("GOT IT", "NIMEIELEWA"),
            ["Prayer.AddTitle"] = ("Add Prayer", "Ongeza Ombi la Maombi"),
            ["Prayer.RequestTitle"] = ("Prayer Request", "Ombi la Maombi"),
            ["Prayer.HowCanWePray"] = ("How can we pray for you?", "Tunawezaje kukuombea?"),
            ["Prayer.ShareHeart"] = ("Share what's on your heart.", "Shiriki yaliyo moyoni mwako."),
            ["Prayer.WriteRequest"] = ("Write your prayer request here...", "Andika ombi lako la maombi hapa..."),
            ["Prayer.Category"] = ("Prayer Category", "Aina ya Ombi la Maombi"),
            ["Prayer.SelectCategory"] = ("Select a category", "Chagua aina"),
            ["Prayer.WhoShouldPray"] = ("Who should pray for you?", "Nani akuombee?"),
            ["Prayer.SelectReach"] = ("Select prayer reach", "Chagua walengwa wa ombi"),
            ["Prayer.WhoCanSeePrayer"] = ("Who can see the prayer?", "Nani anaweza kuona ombi hili?"),
            ["Prayer.Visibility"] = ("Prayer visibility", "Mwonekano wa ombi"),
            ["Prayer.WhoCanSeeName"] = ("Who can see your name?", "Nani anaweza kuona jina lako?"),
            ["Prayer.AuthorVisibility"] = ("Author visibility", "Mwonekano wa jina la mwombaji"),
            ["Prayer.Submit"] = ("🙏 ADD PRAYER", "🙏 TUMA OMBI"),
            ["Prayer.Submitting"] = ("Submitting...", "Inatuma..."),
            ["Prayer.YourPrayer"] = ("My Prayer", "Maombi Yangu"),
            ["Prayer.YourRequestsIntro"] = ("Your prayer requests and the people standing with you.", "Maombi yako na watu wanaokuunga mkono."),
            ["Prayer.YourRequestsEmpty"] = ("Your prayer requests will appear here", "Maombi yako yataonekana hapa"),
            ["Prayer.ShareWithFamily"] = ("Share a prayer request with your USCF family and let others stand with you in prayer.", "Shiriki ombi la maombi na familia yako ya USCF ili wengine wakuunge mkono kwa maombi."),
            ["Prayer.Posted"] = ("Posted {0}", "Imechapishwa {0}"),
            ["Prayer.PrayedWithYou"] = ("🙏  {0} people prayed with you", "🙏  Watu {0} wamekuombea"),
            ["Prayer.IPrayedShort"] = ("✓  I PRAYED", "✓  NIMEOMBA"),
            ["Prayer.Delete"] = ("Delete", "Futa"),
            ["Prayer.LoadingMine"] = ("Loading your prayer requests...", "Maombi yako yanapakia..."),
            ["Prayer.LoadMineError"] = ("We couldn't load your prayer requests. Please check your connection and try again.", "Imeshindikana kupakia maombi yako. Tafadhali angalia muunganisho wako kisha ujaribu tena."),
            ["Prayer.RequestValidationTitle"] = ("Prayer request", "Ombi la Maombi"),
            ["Prayer.WriteBeforeSubmit"] = ("Please write a prayer request before submitting.", "Tafadhali andika ombi la maombi kabla ya kulituma."),
            ["Prayer.CompleteFields"] = ("Please complete every field before submitting.", "Tafadhali jaza sehemu zote kabla ya kutuma."),
            ["Prayer.SharedTitle"] = ("Prayer shared", "Ombi la Maombi Limeshirikiwa"),
            ["Prayer.SharedMessage"] = ("Your prayer request has been shared with the community.", "Ombi lako la maombi limeshirikiwa na jamii."),
            ["Prayer.SubmitError"] = ("We couldn't submit your prayer request.\n{0}", "Imeshindikana kutuma ombi lako la maombi.\n{0}"),
            ["Prayer.NavigationError"] = ("We couldn't open the prayer form. Please try again.", "Imeshindikana kufungua fomu ya maombi. Tafadhali jaribu tena."),
            ["Prayer.ActionError"] = ("We couldn't record your prayer action right now.", "Imeshindikana kurekodi ombi lako kwa sasa."),
            ["Prayer.SaveAction"] = ("Saving...", "Inahifadhi..."),
            ["Prayer.Confirm"] = ("Confirm", "Thibitisha"),
            ["Prayer.DeleteConfirm"] = ("Delete this prayer request?", "Ungependa kufuta ombi hili la maombi?"),
            ["Prayer.NotFound"] = ("Unable to find this prayer request.", "Ombi hili la maombi halijapatikana."),
            ["Prayer.RemovalDisabled"] = ("Prayer removal is not enabled in the current prayer wall release.", "Ufutaji wa maombi haujawezeshwa kwenye toleo hili la ukuta wa maombi."),
            ["Prayer.DeleteError"] = ("Unable to delete prayer request right now.", "Imeshindikana kufuta ombi la maombi kwa sasa."),
            ["Prayer.Option.PrayerCategory.Academic"] = ("Academic", "Masomo"),
            ["Prayer.Option.PrayerCategory.Family"] = ("Family", "Familia"),
            ["Prayer.Option.PrayerCategory.Health"] = ("Health", "Afya"),
            ["Prayer.Option.PrayerCategory.SpiritualGrowth"] = ("Spiritual Growth", "Ukuaji wa Kiroho"),
            ["Prayer.Option.PrayerCategory.Relationships"] = ("Relationships", "Mahusiano"),
            ["Prayer.Option.PrayerCategory.Financial"] = ("Financial", "Fedha"),
            ["Prayer.Option.PrayerCategory.Ministry"] = ("Ministry", "Huduma"),
            ["Prayer.Option.PrayerCategory.Guidance"] = ("Guidance", "Mwongozo"),
            ["Prayer.Option.PrayerCategory.Thanksgiving"] = ("Thanksgiving", "Shukrani"),
            ["Prayer.Option.PrayerCategory.Other"] = ("Other", "Nyingine"),
            ["Prayer.Option.PrayerReach.MyBranch"] = ("My Branch", "Tawi Langu"),
            ["Prayer.Option.PrayerReach.MyDistrict"] = ("My District", "Wilaya Yangu"),
            ["Prayer.Option.PrayerReach.MyRegion"] = ("My Region", "Mkoa Wangu"),
            ["Prayer.Option.PrayerReach.NationalUscf"] = ("National USCF", "USCF Kitaifa"),
            ["Prayer.Option.PrayerReach.PrayerLeaders"] = ("Prayer Leaders", "Viongozi wa Maombi"),
            ["Prayer.Option.PrayerVisibility.Private"] = ("Private", "Binafsi"),
            ["Prayer.Option.PrayerVisibility.SelectedAudience"] = ("Selected Audience", "Watu Waliochaguliwa"),
            ["Prayer.Option.PrayerVisibility.NationalPrayerWall"] = ("National Prayer Wall", "Ukuta wa Maombi wa Kitaifa"),
            ["Prayer.Option.PrayerNameVisibility.Anonymous"] = ("Anonymous", "Bila Jina"),
            ["Prayer.Option.PrayerNameVisibility.ShowMyName"] = ("Show My Name", "Onyesha Jina Langu"),

            ["Community.Title"] = ("Community", "Jamii"),
            ["Community.Connect"] = ("Connect, encourage and grow together.", "Ungana, tia moyo na ukue pamoja."),
            ["Community.TogetherInChrist"] = ("Together in Christ", "Pamoja katika Kristo"),
            ["Community.CreatePost"] = ("Create Post", "Tengeneza Chapisho"),
            ["Community.SharePrompt"] = ("Share your thoughts, prayers or testimony", "Shiriki mawazo, maombi au ushuhuda wako"),
            ["Community.CreatePostDescription"] = ("Create a post", "Tengeneza chapisho"),
            ["Community.FeedDescription"] = ("Open the Church Community feed", "Fungua mtiririko wa jumuiya ya kanisa"),
            ["Community.ChurchCommunity"] = ("Church Community", "Jumuiya ya Kanisa"),
            ["Community.Belong"] = ("A place to share and belong", "Mahali pa kushiriki na kuwa sehemu ya jumuiya"),
            ["Community.Welcome"] = ("Welcome to the CCT community. Share encouragement, Bible verses and testimonies.", "Karibu kwenye jumuiya ya CCT. Shiriki maneno ya kutia moyo, mistari ya Biblia na ushuhuda."),
            ["Community.Explore"] = ("Explore the community feed", "Gundua machapisho ya jamii"),
            ["Community.Discover"] = ("Discover", "Gundua"),
            ["Community.PrayerDescription"] = ("Share your needs and stand with others.", "Shiriki mahitaji yako na uwaunge mkono wengine."),
            ["Community.Announcements"] = ("Church Announcements", "Matangazo ya Kanisa"),
            ["Community.AnnouncementsDescription"] = ("Stay updated with church news and events.", "Pata habari za kanisa na matukio yake."),
            ["Community.Groups"] = ("Church Groups", "Vikundi vya Kanisa"),
            ["Community.GroupsDescription"] = ("Connect and grow in faith together.", "Ungana na ukue katika imani pamoja."),
            ["Community.OpenPrayer"] = ("Open Prayer Requests", "Fungua Maombi"),
            ["Community.OpenAnnouncements"] = ("Open Church Announcements", "Fungua Matangazo ya Kanisa"),
            ["Community.OpenGroups"] = ("Open Church Groups", "Fungua Vikundi vya Kanisa"),
            ["Community.NotAuthenticated"] = ("Not authenticated", "Hujaingia"),
            ["Community.SignInToPost"] = ("Please sign in to create posts.", "Tafadhali ingia ili kutengeneza machapisho."),
            ["Community.PostDestination"] = ("Where do you want to post?", "Ungependa kuchapisha wapi?"),
            ["Community.Cancel"] = ("Cancel", "Ghairi"),
            ["Community.NationalGroup"] = ("National Group", "Kikundi cha Kitaifa"),
            ["Community.RegionalGroup"] = ("Regional Group", "Kikundi cha Kanda"),
            ["Community.DistrictGroup"] = ("District Group", "Kikundi cha Wilaya"),
            ["Community.BranchGroup"] = ("Branch Group", "Kikundi cha Tawi"),
            ["Community.FullCommunity"] = ("Full Community", "Jumuiya Nzima"),

            ["Profile.Title"] = ("Profile", "Wasifu"),
            ["Profile.Account"] = ("ACCOUNT", "AKAUNTI"),
            ["Profile.MyProfile"] = ("My Profile", "Wasifu Wangu"),
            ["Profile.FullName"] = ("Full Name", "Jina Kamili"),
            ["Profile.Member"] = ("CCT-USCF member", "Mwanachama wa CCT-USCF"),
            ["Profile.Contact"] = ("CONTACT INFORMATION", "TAARIFA ZA MAWASILIANO"),
            ["Profile.Username"] = ("Username", "Jina la Mtumiaji"),
            ["Profile.Email"] = ("Email", "Barua Pepe"),
            ["Profile.Phone"] = ("Phone Number", "Namba ya Simu"),
            ["Profile.Membership"] = ("MEMBERSHIP DETAILS", "TAARIFA ZA UANACHAMA"),
            ["Profile.Role"] = ("Role", "Wadhifa"),
            ["Profile.Branch"] = ("USCF Branch", "Tawi la USCF"),
            ["Profile.Region"] = ("Region", "Mkoa"),
            ["Profile.District"] = ("District", "Wilaya"),
            ["Profile.SignOut"] = ("Sign out", "Toka"),
            ["Profile.YourUscf"] = ("YOUR CCT-USCF", "CCT-USCF YAKO"),
            ["Profile.SavedVerses"] = ("Saved Bible Verses", "Mistari ya Biblia Iliyohifadhiwa"),
            ["Profile.MyPrayerRequests"] = ("My Prayer Requests", "Maombi Yangu"),
            ["Profile.SavedSermons"] = ("Saved Sermons", "Mahubiri Yaliyohifadhiwa"),
            ["Profile.MyEvents"] = ("My Events", "Matukio Yangu"),
            ["Profile.RateUscf"] = ("Rate USCF", "Kadiria USCF"),
            ["Profile.RatePrompt"] = ("Enjoying CCT-USCF? Share your experience.", "Unafurahia CCT-USCF? Shiriki uzoefu wako."),
            ["Profile.HelpSupport"] = ("Help & Feedback", "Msaada na Maoni"),
            ["Profile.HelpPrompt"] = ("Get help, ask a question, or share feedback.", "Pata msaada, uliza swali au toa maoni."),
            ["Profile.Settings"] = ("Settings", "Mipangilio"),
            ["Profile.Logout"] = ("⇥   Logout", "⇥   Toka"),
            ["Profile.NotAvailable"] = ("Not available", "Haipatikani"),
            ["Profile.UnableToLoad"] = ("Unable to load", "Imeshindikana kupakia"),

            ["Settings.Title"] = ("Settings", "Mipangilio"),
            ["Settings.Account"] = ("Account Settings", "Mipangilio ya Akaunti"),
            ["Settings.FullName"] = ("Full name", "Jina kamili"),
            ["Settings.Username"] = ("Username", "Jina la mtumiaji"),
            ["Settings.EmailFirebase"] = ("Email (managed by Firebase)", "Barua pepe (inasimamiwa na Firebase)"),
            ["Settings.Phone"] = ("Phone number", "Namba ya simu"),
            ["Settings.ChangePassword"] = ("Change Password", "Badilisha Nenosiri"),
            ["Settings.CurrentPassword"] = ("Current password", "Nenosiri la sasa"),
            ["Settings.NewPassword"] = ("New password", "Nenosiri jipya"),
            ["Settings.ConfirmPassword"] = ("Confirm new password", "Thibitisha nenosiri jipya"),
            ["Settings.SaveChanges"] = ("Save Changes", "Hifadhi Mabadiliko"),
            ["Settings.GroupSettings"] = ("Group Settings", "Mipangilio ya Kikundi"),
            ["Settings.GroupDeactivateInfo"] = ("Only this group's authorized creator or administrator can deactivate it.", "Ni mtengenezaji au msimamizi aliyeidhinishwa pekee anayeweza kuzima kikundi hiki."),
            ["Settings.DeleteGroup"] = ("Delete group", "Futa kikundi"),
            ["Settings.DeleteAccount"] = ("Delete account", "Futa akaunti"),
            ["Settings.DeleteAccountWarning"] = ("This permanently deletes your Firebase account and CCT-USCF Firestore profile. This action cannot be undone.", "Hii itafuta kabisa akaunti yako ya Firebase na wasifu wako wa CCT-USCF Firestore. Kitendo hiki hakiwezi kutenduliwa."),
            ["Settings.DeleteMyAccount"] = ("Delete my account", "Futa akaunti yangu"),
            ["Settings.Assistance"] = ("USCF Assistance", "Msaada wa USCF"),
            ["Settings.AssistancePrompt"] = ("Get contextual help across CCT-USCF.", "Pata msaada unaohusiana na sehemu mbalimbali za CCT-USCF."),
            ["Settings.LanguageAppearance"] = ("Language & Appearance", "Lugha na Mwonekano"),
            ["Settings.AppLanguage"] = ("🌐 App Language", "🌐 Lugha ya Programu"),
            ["Settings.ChooseLanguage"] = ("Choose language", "Chagua lugha"),
            ["Settings.AppBackground"] = ("🎨 App Background", "🎨 Mandhari ya Programu"),
            ["Settings.ChooseBackground"] = ("Choose background", "Chagua mandhari"),
            ["Settings.Preview"] = ("Preview", "Onyesho la Awali"),
            ["Settings.CustomColor"] = ("Custom color (#RRGGBB)", "Rangi maalum (#RRGGBB)"),
            ["Settings.ApplyAppearance"] = ("Apply appearance", "Tumia mwonekano"),
            ["Settings.ChatTypography"] = ("Chat Typography", "Muonekano wa Maandishi ya Gumzo"),
            ["Settings.FontPreference"] = ("Font preference", "Chaguo la aina ya herufi"),
            ["Settings.FontSize"] = ("Font size", "Ukubwa wa herufi"),
            ["Settings.Background.System"] = ("System", "Mfumo"),
            ["Settings.Background.White"] = ("White", "Nyeupe"),
            ["Settings.Background.Blue"] = ("Blue", "Bluu"),
            ["Settings.Background.Green"] = ("Green", "Kijani"),
            ["Settings.Background.Cream"] = ("Cream", "Krimu"),
            ["Settings.Background.Purple"] = ("Purple", "Zambarau"),
            ["Settings.Background.Gray"] = ("Gray", "Kijivu"),
            ["Settings.Background.Dark"] = ("Dark", "Giza"),
            ["Settings.Background.SoftGradient"] = ("Soft gradient", "Mchanganyiko laini wa rangi"),
            ["Settings.Background.Custom"] = ("Custom", "Maalum"),
            ["Settings.Font.System"] = ("System", "Mfumo"),
            ["Settings.Font.Small"] = ("Small", "Ndogo"),
            ["Settings.Font.Medium"] = ("Medium", "Wastani"),
            ["Settings.Font.Large"] = ("Large", "Kubwa"),
            ["Settings.AppearanceInvalidColor"] = ("Use a valid color such as #336699.", "Tumia rangi sahihi kama #336699."),
            ["Settings.AppearanceApplied"] = ("Appearance settings applied.", "Mipangilio ya mwonekano imetumika."),
            ["Settings.DeleteGroupConfirmTitle"] = ("Delete group?", "Futa kikundi?"),
            ["Settings.DeleteGroupConfirmMessage"] = ("This will deactivate this group for all members.", "Hii itazima kikundi hiki kwa wanachama wote."),
            ["Settings.GroupDeletedTitle"] = ("Group deleted", "Kikundi kimefutwa"),
            ["Settings.GroupUnavailable"] = ("The group is no longer available.", "Kikundi hiki hakipatikani tena."),
            ["Settings.DeleteGroupError"] = ("Unable to delete group", "Imeshindikana kufuta kikundi"),
            ["Settings.NotAuthenticated"] = ("Not authenticated", "Hujaingia"),
            ["Settings.SignIn"] = ("Please sign in.", "Tafadhali ingia."),
            ["Settings.Error"] = ("Error", "Hitilafu"),
            ["Settings.Validation"] = ("Validation", "Uhakiki"),
            ["Settings.FullNameRequired"] = ("Full name is required.", "Jina kamili linahitajika."),
            ["Settings.UsernameRequired"] = ("Username is required.", "Jina la mtumiaji linahitajika."),
            ["Settings.EmailRequired"] = ("Email is required.", "Barua pepe inahitajika."),
            ["Settings.CurrentPasswordRequired"] = ("Current password is required to change password.", "Nenosiri la sasa linahitajika ili kulibadilisha."),
            ["Settings.PasswordMismatch"] = ("New password and confirmation do not match.", "Nenosiri jipya na uthibitisho wake havilingani."),
            ["Settings.UpdateProfileError"] = ("Unable to update profile.", "Imeshindikana kusasisha wasifu."),
            ["Settings.Success"] = ("Success", "Imefanikiwa"),
            ["Settings.ProfileUpdated"] = ("Profile updated.", "Wasifu umesasishwa."),
            ["Settings.DeleteAccountConfirmTitle"] = ("Delete account?", "Futa akaunti?"),
            ["Settings.DeleteAccountConfirmMessage"] = ("This permanently deletes your Firebase account and CCT-USCF Firestore profile. This action cannot be undone.", "Hii itafuta kabisa akaunti yako ya Firebase na wasifu wako wa CCT-USCF Firestore. Kitendo hiki hakiwezi kutenduliwa."),
            ["Settings.DeleteAccountConfirm"] = ("Delete account", "Futa akaunti"),
            ["Settings.AccountDeletedTitle"] = ("Account deleted", "Akaunti imefutwa"),
            ["Settings.AccountDeletedMessage"] = ("Your account and profile have been deleted.", "Akaunti na wasifu wako vimefutwa."),
            ["Settings.AccountDeletion"] = ("Account deletion", "Ufutaji wa akaunti"),
            ["Common.Ok"] = ("OK", "Sawa"),
            ["Common.Delete"] = ("Delete", "Futa"),
            ["Common.Cancel"] = ("Cancel", "Ghairi")
        };

    public static string Get(string key, string language)
    {
        if (!Strings.TryGetValue(key, out var value))
            throw new KeyNotFoundException($"Missing application localization key '{key}'.");

        return string.Equals(language, "sw", StringComparison.OrdinalIgnoreCase)
            ? value.Swahili
            : value.English;
    }

    public static void Apply(ResourceDictionary resources, string language)
    {
        foreach (var (key, _) in Strings)
            resources[$"AppText_{key.Replace('.', '_')}"] = Get(key, language);
    }
}

public sealed class LocalizedPrayerEnumConverter : IValueConverter
{
    public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is not Enum enumValue)
            return value?.ToString() ?? string.Empty;

        return MauiProgram.Services
            .GetRequiredService<AppAppearanceService>()
            .GetText($"Prayer.Option.{enumValue.GetType().Name}.{enumValue}");
    }

    public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture) =>
        throw new NotSupportedException();
}
