CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "BiblePosts" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "PostType" text NOT NULL,
        "BookId" text NOT NULL,
        "ChapterNumber" integer NOT NULL,
        "VerseStart" integer NOT NULL,
        "VerseEnd" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_BiblePosts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "BibleVerses" (
        "Id" uuid NOT NULL,
        "Book" character varying(200) NOT NULL,
        "Chapter" integer NOT NULL,
        "VerseNumber" integer NOT NULL,
        "Text" text NOT NULL,
        "AudioReference" text,
        "AudioDurationSeconds" integer,
        "AudioFileSizeBytes" bigint,
        "AudioMimeType" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BibleVerses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "Posts" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Content" text NOT NULL,
        "Caption" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Posts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "Regions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Regions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "PostMedias" (
        "Id" uuid NOT NULL,
        "PostId" uuid NOT NULL,
        "MediaType" text NOT NULL,
        "FileName" text NOT NULL,
        "Url" text,
        "StoragePath" text,
        "Duration" double precision,
        "TrimStart" double precision,
        "TrimEnd" double precision,
        "FileSizeBytes" bigint,
        "UploadedByUserId" uuid,
        "IsTemporary" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "DeletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PostMedias" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PostMedias_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "Districts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "RegionId" integer NOT NULL,
        CONSTRAINT "PK_Districts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Districts_Regions_RegionId" FOREIGN KEY ("RegionId") REFERENCES "Regions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "Branches" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "DistrictId" integer NOT NULL,
        CONSTRAINT "PK_Branches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Branches_Districts_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Districts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "Username" character varying(100) NOT NULL,
        "Email" character varying(320) NOT NULL,
        "PasswordHash" text NOT NULL,
        "PhoneNumber" character varying(20),
        "ProfileImageUrl" text,
        "Bio" text,
        "Role" character varying(50) NOT NULL,
        "RegionId" integer,
        "DistrictId" integer,
        "BranchId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "LastSeenAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "RefreshTokenHash" character varying(512),
        "RefreshTokenExpiresAt" timestamp with time zone,
        "RoleVerificationStatus" character varying(50) NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Users_Districts_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Districts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Users_Regions_RegionId" FOREIGN KEY ("RegionId") REFERENCES "Regions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE TABLE "PrayerRequests" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "Status" character varying(50) NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PrayerRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PrayerRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_BibleVerses_Book_Chapter_VerseNumber" ON "BibleVerses" ("Book", "Chapter", "VerseNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_Branches_DistrictId" ON "Branches" ("DistrictId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_Districts_RegionId" ON "Districts" ("RegionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_PostMedias_PostId_CreatedAt" ON "PostMedias" ("PostId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_PrayerRequests_UserId_CreatedAtUtc" ON "PrayerRequests" ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_Users_BranchId" ON "Users" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_Users_DistrictId" ON "Users" ("DistrictId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE INDEX "IX_Users_RegionId" ON "Users" ("RegionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260825142619_InitialPostgreSql') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260825142619_InitialPostgreSql', '10.0.0');
    END IF;
END $EF$;
COMMIT;

